version: "3.5"  # optional since v1.27.0
services:
  rabbit-1:
    image: rabbitmq:3.8-management
    hostname: rabbit-1
    container_name: rabbit-1
    volumes:
      - ${PWD}/config/rabbit-1:/config/    
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_CONFIG_FILE: /config/rabbitmq
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbit-network
  rabbit-2:
    image: rabbitmq:3.8-management
    hostname: rabbit-2
    depends_on:
      - rabbit-1
    container_name: rabbit-2
    volumes:
      - ${PWD}/config/rabbit-2:/config/
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_CONFIG_FILE: /config/rabbitmq
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    ports:
      - 5673:5672
      - 15673:15672
    networks:
      - rabbit-network
  rabbit-3:
    image: rabbitmq:3.8-management
    hostname: rabbit-3
    depends_on:
      - rabbit-1
    container_name: rabbit-3
    volumes:
      - ${PWD}/config/rabbit-3:/config/
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_CONFIG_FILE: /config/rabbitmq
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    ports:
      - 5674:5672
      - 15674:15672
    networks:
      - rabbit-network
  nginx:
    depends_on:
      - rabbit-1
      - rabbit-2
      - rabbit-3
    image: nginx
    container_name: nginx
    ports:
      - "5000:80"
      - "15000:15000"
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/nginx/log:/var/log/nginx/
    networks:
      - rabbit-network
networks:
  rabbit-network:
